version: '3'

services:
 backendproj:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   volumes: ["./backendproj:/opt/backendproj"]
   environment:
     PORT: "5000"
     FLASK_DEBUG: "true"
   ports:
     - "5000:5000"
